### PR TITLE
Preload encounters on hover

### PR DESCRIPTION
**Pull request by anyduck**
## Features
- Reduced loading delay for encounter info by 2x (old code was doing it twice)
- Improved user experience by preloading encounter info on hover (SvelteKit magic)

### CODE REVIEW

**Comment by anyduck** [comment]
It should feel even better, if we preload when hovering over a table row, but that'll require making the whole row a clickable link. Should I do it?

It looks like there is also a way to do this by listening to the `MouseEnter` event and calling `import { preloadData } from '$app/navigation';`

**Comment by snoww** [comment]
feel free to try it out and see how it goes

**Comment by anyduck** [comment]
I'll leave it as it is now

It had some stutters while using `on:mouseenter` for preload

**Comment by anyduck** [comment]
Sorry for the force pushes, I made a crappy rebase

**Pull request merged**
